---
abstract: 'Handy CLI HTTP tool'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Adenosine
requires:
  Capture::Tiny: 0
  Config::Any: 0
  File::HomeDir: 0
  File::Path: 0
  File::Spec::Functions: 0
  File::Temp: 0
  File::pushd: 0
  FindBin: 0
  Getopt::Long: 0
  JSON: 2.53
  Module::Runtime: 0
  Moo: 1.000006
  Path::Class: 0.26
  Scalar::Util: 0
  Test::Deep: 0
  Test::More: 0
  Text::ParseWords: 0
  Time::HiRes: 0
  URI: 0
  URI::Escape: 0
  YAML: 0
resources:
  bugtracker: http://github.com/frioux/app-adenosine/issues
  repository: git://github.com/frioux/app-adenosine.git
version: 2.001006
